apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ticket-ebs-test
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-storage
  resources:
    requests:
      storage: 10Gi
