apiVersion: v1
kind: Pod
metadata:
  name: secret-test
  namespace: default
spec:
  serviceAccountName: ticket-backend-sa
  containers:
    - name: test
      image: 234632868467.dkr.ecr.ap-south-1.amazonaws.com/ticket-backend:1.2
      command:
        - sh
        - -c
        - |
          echo "=== SQL Username ==="
          cat /mnt/secrets-store/sql-username
          echo
          echo "=== SQL Password ==="
          wc -c /mnt/secrets-store/sql-password
          echo "Secret retrieval successful"
          sleep 3600
      volumeMounts:
        - name: secrets-store
          mountPath: /mnt/secrets-store
          readOnly: true
  volumes:
    - name: secrets-store
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: ticket-backend-secrets
